In [12]:
x= [5,6,7,0,0,0]
y = [1,2,3]
m, n = 3,3

In [19]:
def merge(num1, m, num2, n):
    x, y = m-1, n-1
    
    for p in range(m+n-1, -1, -1): 
        
        if y < 0:
            break 
        
        if x >= 0 and num1[x] > num2[y]:
            num1[p] = num1[x]
            x -= 1 
        else:
            num1[p] = num2[y]
            y -= 1
        
   
num1= [4,6,7,0,0,0]
num2 = [1,2,5]
m, n = 3,3
merge(num1, m, num2, n )

print(num1)

[1, 2, 4, 5, 6, 7]


In [15]:
for i in range(10, -1, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0


In [22]:
def find_max(x: "prajwal"): 
    
    min_invest = float("inf")
    max_profit = 0
    
    for i in range(len(x)): 
        
        if min_invest > x[i]: 
            min_invest = x[i]
        
        profit = x[i] - min_invest
        if profit > max_profit:
            max_profit = profit
    return max_profit
    
find_max([7,1,6,5,4,8])
        
    

7

In [25]:
list(itertools.combinations([1,2,3,5,6], r =3))

[(1, 2, 3),
 (1, 2, 5),
 (1, 2, 6),
 (1, 3, 5),
 (1, 3, 6),
 (1, 5, 6),
 (2, 3, 5),
 (2, 3, 6),
 (2, 5, 6),
 (3, 5, 6)]

In [29]:
import numpy as np
from typing import Union
class VahidMatrix:
    
    def __init__(self, mat : Union[list, np.array]) -> None:
        self.data = np.array(mat)
        self.rows, self.columns = self.data.shape

    def __mul__(self, mat2 : "VahidMatrix")-> "VahidMatrix":
        r2, c2 = mat2.rows, mat2.columns
        
        if self.columns != r2:
            raise ValueError("These c....")
        
        reult = np.zeros((self.rows, c2))
        
        for i in range(self.rows):
            for j in range(c2):
                for k in range(self.columns):
                    
                    reult[i,j] += self.data[i,k] * mat2.data[k,j]
                    
        return VahidMatrix(reult)

    def __repr__(self):
        return str(self.data)


matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix2 = [
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
]

m1 = VahidMatrix(matrix1)
m2 = VahidMatrix(matrix2)



In [30]:
m1*m2

[[ 21.  27.  33.]
 [ 57.  72.  87.]
 [ 93. 117. 141.]]

In [31]:
np.array(matrix1) @ np.array(matrix2)

array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]])