In [23]:
import pandas as pd
from copy import deepcopy
# Read csv file 
df = pd.read_csv("mtcars.csv", delimiter=",")

# print the dataframe head
df.head()

Unnamed: 0       vichle_names   mpg  cyl   disp     hp  drat     wt   qsec  \
0           0          Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   
1           1      Mazda RX4 Wag  21.0    6  160.0  110.0  3.90  2.875  17.02   
2           2         Datsun 710   NaN    4  108.0   93.0  3.85  2.320  18.61   
3           3     Hornet 4 Drive  21.4    6  258.0    NaN  3.08  3.215  19.44   
4           4  Hornet Sportabout  18.7    8  360.0  175.0  3.15  3.440  17.02   

   v_Shape   am  gear  carb  
0      0.0  1.0   4.0     4  
1      0.0  1.0   4.0     4  
2      1.0  1.0   4.0     1  
3      1.0  0.0   3.0     1  
4      0.0  0.0   NaN     2

In [12]:
# print the dataframe shape 
print("Total Rows:{} Columns:{}".format(df.shape[0],df.shape[1]))

Total Rows:32 Columns:13


In [13]:
# print dataframe stats of numerical columns.
df.describe()

Unnamed: 0        mpg        cyl        disp          hp       drat  \
count   32.000000  30.000000  32.000000   32.000000   31.000000  31.000000   
mean    15.500000  20.076667   6.187500  230.721875  147.870968   3.609032   
std      9.380832   6.196366   1.785922  123.938694   69.363171   0.538766   
min      0.000000  10.400000   4.000000   71.100000   52.000000   2.760000   
25%      7.750000  15.275000   4.000000  120.825000   96.000000   3.080000   
50%     15.500000  19.200000   6.000000  196.300000  123.000000   3.700000   
75%     23.250000  22.475000   8.000000  326.000000  180.000000   3.920000   
max     31.000000  33.900000   8.000000  472.000000  335.000000   4.930000   

              wt       qsec    v_Shape         am       gear     carb  
count  32.000000  29.000000  30.000000  28.000000  29.000000  32.0000  
mean    3.217250  17.601379   0.433333   0.428571   3.724138   2.8125  
std     0.978457   1.535459   0.504007   0.503953   0.751026   1.6152  
min     1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%     2.581250  16.870000   0.000000   0.000000   3.000000   2.0000  
50%     3.325000  17.420000   0.000000   0.000000   4.000000   2.0000  
75%     3.610000  18.610000   1.000000   1.000000   4.000000   4.0000  
max     5.424000  20.010000   1.000000   1.000000   5.000000   8.0000

In [14]:
# Check missing values 
df.isnull().sum()

Unnamed: 0      0
vichle_names    0
mpg             2
cyl             0
disp            0
hp              1
drat            1
wt              0
qsec            3
v_Shape         2
am              4
gear            3
carb            0
dtype: int64

In [16]:
# Check missing the ratio 
df.isnull().mean() * 100

Unnamed: 0       0.000
vichle_names     0.000
mpg              6.250
cyl              0.000
disp             0.000
hp               3.125
drat             3.125
wt               0.000
qsec             9.375
v_Shape          6.250
am              12.500
gear             9.375
carb             0.000
dtype: float64

In [28]:
missing_colums = list(df.columns[df.isna().any()])

In [27]:
mean_fill_df = deepcopy(df)
mode_fill_df = deepcopy(df)


# Relace with mean 
for col in missing_colums:
    mean_fill_df[col].fillna(value=df[col].mean(),inplace=True)

# Replae with mode
for col in missing_colums:
    mode_fill_df[col].fillna(value=df[col].mode(),inplace=True)

C:\Users\RJNGh\AppData\Local\Temp\ipykernel_4596\1373681891.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mean_fill_df[col].fillna(value=df[col].mean(),inplace=True)
C:\Users\RJNGh\AppData\Local\Temp\ipykernel_4596\1373681891.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy

In [34]:
# get datatypes
df.dtypes

Unnamed: 0        int64
vichle_names     object
mpg             float64
cyl               int64
disp            float64
hp              float64
drat            float64
wt              float64
qsec            float64
v_Shape         float64
am              float64
gear            float64
carb              int64
dtype: object

In [45]:
# get all the numerical columns
numerical_cols = list(df._get_numeric_data().columns)

# get all the categorical columns
categorical_columns = set(df.columns) - set(numerical_cols)

# check we extracted all the columns
assert len(numerical_cols) + len(categorical_columns) == len(list(df.columns))

### Create Dataframe

In [48]:
data_dict = {
    "Name" : ["Rajan","Ghimire","Sudip","Arjan"],
    "SRN" : [1,2,3,4],
    "GPA" : [1.0,2.0,3.9,3.9]
}
# create dataframe obj from dict
df_custom = pd.DataFrame(data_dict)

# print the new dataframe head 
df_custom.head()

Name  SRN  GPA
0    Rajan    1  1.0
1  Ghimire    2  2.0
2    Sudip    3  3.9
3    Arjan    4  3.9

In [50]:
# get the index of my name 
df_custom.loc[df_custom.Name == "Rajan"].index

Index([0], dtype='int64')

In [56]:
# Remanme index 
df_custom.index.name = "my_index"

# print df head 
df_custom.head()

Name  SRN  GPA
my_index                   
0           Rajan    1  1.0
1         Ghimire    2  2.0
2           Sudip    3  3.9
3           Arjan    4  3.9

In [59]:
df_custom.to_csv("1.csv")

In [60]:
df_custom.to_json("1.json")

In [5]:
# generate random data
from sklearn.datasets import make_regression, make_classification


In [2]:
features, target, coff = make_regression(
    n_samples= 100,
    n_features=3,
    n_informative=3, # The number of informative features, i.e., the number of features used to build the linear model used to generate the output.
    n_targets=1,
    noise=0.0,
    coef= True,
    random_state=1
)

In [3]:
print(f"Feature : {features} \n Target : {target}")

Feature : [[ 1.29322588e+00 -6.17362064e-01 -1.10447026e-01]
 [-2.79308500e+00  3.66332015e-01  1.93752881e+00]
 [ 8.01861032e-01 -1.86569772e-01  4.65672984e-02]
 [ 1.29101580e-01  5.02740882e-01  1.61694960e+00]
 [-6.91660752e-01 -6.87172700e-01 -3.96753527e-01]
 [-7.54397941e-01  5.12929820e-01  1.25286816e+00]
 [ 1.90465871e+00  6.59049796e-01  1.11105670e+00]
 [ 2.01830179e-01  1.79215821e+00  6.61020288e-01]
 [ 4.22137467e-02 -1.10061918e+00  5.82815214e-01]
 [-1.39649634e+00 -5.04465863e-01 -1.44411381e+00]
 [-3.10116774e-01  1.03882460e+00 -2.43483776e+00]
 [ 8.36004719e-01  7.58805660e-01  1.54335911e+00]
 [-8.45080274e-02  4.17302005e-01 -2.97361883e-01]
 [-8.90555584e-01  1.95607890e+00 -1.11911540e+00]
 [-9.35769434e-01  5.30355467e-01 -2.67888080e-01]
 [ 1.55880554e+00 -1.21974440e+00  1.09402696e-01]
 [ 8.10951673e-01 -4.00878192e-01  1.04444209e+00]
 [ 4.36689932e-02  1.33145711e+00 -2.26314243e-01]
 [ 7.42044161e-01 -8.87628964e-01 -1.91835552e-01]
 [ 1.69382433e-01 -9.

In [4]:
coff

array([44.19042807, 98.97517077, 58.15774073])

In [6]:
features, target  = make_classification(
    n_samples=100,
    n_features=3,
    n_informative=3,
    n_redundant=0,
    n_classes=2,
    weights=[.25,.75],
    random_state=1
)

In [8]:
print(features),print(target)

[[ 1.06354768e+00 -1.42632219e+00  1.02163151e+00]
 [ 2.31569771e-01  1.49535261e+00  3.32515785e-01]
 [ 1.59729509e-01  8.35335154e-01 -4.08695544e-01]
 [-7.06121328e-01 -1.03281003e+00  1.39477986e+00]
 [ 8.44490198e-01 -6.19971892e-01  1.08791124e+00]
 [ 5.59394552e-01 -1.45815378e+00  1.47602390e+00]
 [-2.34279989e+00 -8.62141541e-01 -7.02236503e-01]
 [-5.02301432e-01 -1.11266501e+00  9.94591165e-01]
 [ 9.18051403e-01 -1.31813097e+00  1.37672287e+00]
 [-6.37174666e-01  5.90888879e-01 -2.20412713e-01]
 [ 1.27505434e+00  1.81333214e+00 -1.76262615e-01]
 [-8.44318348e-02 -8.41896666e-01  1.27619816e+00]
 [ 1.17033878e+00 -2.50462535e-01  6.51088535e-02]
 [ 1.86526206e+00 -1.44673919e+00  5.82315275e-01]
 [-4.51512990e-01 -1.00104693e+00  1.42523865e+00]
 [-1.52227032e+00 -9.58868332e-01  9.82710762e-01]
 [-7.51474297e-01 -9.71645767e-01  9.59587901e-01]
 [ 9.79144440e-01 -3.36999556e-01  4.07143853e-01]
 [ 8.86706299e-01 -1.18285338e+00  1.49055825e+00]
 [-1.29255057e+00 -8.91797450e-

(None, None)

In [22]:

data = {
    "features_0" : [x[0] for x in features],
    "features_1" : [x[1] for x in features],
    "features_2" : [x[2] for x in features],
    "target" : target
}

In [23]:
df = pd.DataFrame(data=data)

In [24]:
df.head()

features_0  features_1  features_2  target
0    1.063548   -1.426322    1.021632       1
1    0.231570    1.495353    0.332516       0
2    0.159730    0.835335   -0.408696       0
3   -0.706121   -1.032810    1.394780       1
4    0.844490   -0.619972    1.087911       1

In [42]:
import numpy as np 

stacked = np.column_stack((features, target))

df2 = pd.DataFrame(stacked, columns=['feature_1',"feature_2","feature_3","target"])

df2.head()

feature_1  feature_2  feature_3  target
0   1.063548  -1.426322   1.021632     1.0
1   0.231570   1.495353   0.332516     0.0
2   0.159730   0.835335  -0.408696     0.0
3  -0.706121  -1.032810   1.394780     1.0
4   0.844490  -0.619972   1.087911     1.0

In [43]:
from sklearn.datasets import make_blobs
features, classes = make_blobs(n_samples=100,centers=3,n_features=2,random_state=0)

df = pd.DataFrame(data=features,columns=["feature1","feature2"])
df["cluster_id"] = classes

In [46]:
import plotly.express as px 
fig = px.scatter(df,x = 'feature1',y="feature2",color='cluster_id')
fig.show()