Q1) Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.

Note: You must not use any built-in BigInteger library or convert the inputs to integer directly.

 

Example 1:

Input: num1 = "2", num2 = "3"

Output: "6"

In [26]:
import random
import unittest

def multiply_two_strings(num1: str, num2 : str)-> str:
    
    # check if any of the number in 0:
    if '0' in [num1 , num2]:
        return '0'
    
    # length of the reuslt 
    result = [0] * ((len(num1) + len(num1)))
    
    num1, num2 = num1[::-1], num2[::-1] 
    
    for i in range(len(num1)):
        for j in range(len(num2)):
            
            digit = int(num1[i]) * int(num2[j])
            
    
            
            result[i+j] += digit
            result[i+j+1] += (result[i+j] // 10)
            result[i+j] = result[i+j] % 10

    result = result[::-1]
    if result[0] == 0:
        result = result[1:]
        
    return "".join([str(x) for x in result])


for _ in range(3):
    num1= random.randint(a=1,b=9999)
    num2= random.randint(a=1,b=9999)
    print(f"{num1} * {num2} == {num2 * num1}")
    print(multiply_two_strings(str(num1),str(num2)))


5755 * 4780 == 27508900
27508900
4036 * 3057 == 12338052
12338052
1248 * 6104 == 7617792
7617792


) The count-and-say sequence is a sequence of digit strings defined by the recursive formula:

countAndSay(1) = "1"
countAndSay(n) is the way you would "say" the digit string from countAndSay(n-1), which is then converted into a different digit string.

In [64]:

def convert_count_(s):
    
    result = ""
    count = 1
    for i in range(len(s)-1):
        if s[i] == s[i+1]:
            count +=1
            
        else:
            result = result + str(count) + str(s[i])
            count = 1
        
    # add last digit 
    result = result + str(count) + str(s[-1])
    
    return result
        
        
def solve(n):
    if n==1:
        return "1"
    counter = 2
    ans = "1"
    while counter <= n:
        ans = convert_count_(s=ans)

        counter +=1

    return ans

solve(4)

'1211'

In [127]:
def mul_2_string(s1,s2):
    if "0" in [s1,s2]:
        return "0"

    result = [0] * (len(s1) + len(s2))
    s1,s2 = s1[::-1],s2[::-1]
    for i in range(len(s1)):
        for j in range(len(s2)):
            
            # get the digit
            digit = int(s1[i]) * int(s2[j])
            
            result[i+j] += digit
            result[i+j+1]= (result[i+j]) // 10
            result[i+j]= (result[i+j]) % 10
    
    
    print(result[::-1])
            

In [128]:
mul_2_string(s1="12",s2="12")

[0, 1, 4, 4]


In [1]:
def solver(s : str):
    count = 1 
    answer = ""
    
    for i in range(len(s)-1):
        if s[i] == s[i+1]:
            count += 1
        else:
            answer = answer + str(count) + str(s[i])
            count = 1
    
    answer = answer + str(count) + str(s[-1])
    
    return answer
    

In [3]:
solver("aaabbcca")

'3a2b2c1a'

In [4]:
import numpy as np

In [6]:
np.arange(1,28)

array([ 1.        ,  1.55102041,  2.10204082,  2.65306122,  3.20408163,
        3.75510204,  4.30612245,  4.85714286,  5.40816327,  5.95918367,
        6.51020408,  7.06122449,  7.6122449 ,  8.16326531,  8.71428571,
        9.26530612,  9.81632653, 10.36734694, 10.91836735, 11.46938776,
       12.02040816, 12.57142857, 13.12244898, 13.67346939, 14.2244898 ,
       14.7755102 , 15.32653061, 15.87755102, 16.42857143, 16.97959184,
       17.53061224, 18.08163265, 18.63265306, 19.18367347, 19.73469388,
       20.28571429, 20.83673469, 21.3877551 , 21.93877551, 22.48979592,
       23.04081633, 23.59183673, 24.14285714, 24.69387755, 25.24489796,
       25.79591837, 26.34693878, 26.89795918, 27.44897959, 28.        ])

In [12]:
class X:
    def __init__(self) -> None:
        self.value = np.ndarray([1,2,3])
    
    def __str__(self) -> str:
        return str(self.value)
    
    # def __repr__(self) -> str:
    #     return self.value(str)

In [13]:
x = X()

In [14]:
print(x)

[[[1.14155722e-313 0.00000000e+000 6.92910763e-310]
  [6.92910763e-310 6.92910763e-310 4.67581765e-310]]]


In [15]:
def f(x, l=[]):
    for i in range(x):
        l.append(i*i)
    print(l)

print(f(2))
print(f(3, [3, 2, 1]))
print(f(3))

[0, 1]
None
[3, 2, 1, 0, 1, 4]
None
[0, 1, 0, 1, 4]
None
