In [22]:
import numpy as np
from typing import List, Union
class Matrix:
    
    def __init__(self, data: Union[list, np.ndarray] ) -> None:
        self.data = np.array(data) 
        self.rows , self.columns = self.data.shape
        
        
    def __mul__(self, matrix : 'Matrix') -> 'Matrix':
        
        if not isinstance(matrix, Matrix):
            raise ValueError("Cannot multiply other data type.")
        
        if self.columns != matrix.rows:
            raise ValueError("Shape mismatch, cannot multuply these matrices.")
        
        # initialize the resultant matrix:
        result = np.zeros((self.rows, matrix.columns))
        
        # perform the matrix multiplication 
        for i in range(self.rows):
            for j in range(matrix.columns):
                for k in range(self.columns):
                    result[i,j] += self.data[i,k] * matrix.data[k,j]
                    
        return Matrix(result)
    
    
    def Transpose(self):
        # resultant matrix 
        transpose = np.zeros((self.rows, self.columns))
        for i in range(self.rows):
            for j in range(self.columns):
                transpose[j][i] = self.data[i][j]
                 
        return Matrix(transpose)
                
    
    def __repr__(self) -> str:
        return str(self.data)
    

matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix2 = [
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
]

m1 = Matrix(matrix1)
m2 = Matrix(matrix2)


**Reverse a integer.**

In [31]:
def reverse_integer( x : int) -> int:
    
    is_neg = x < 0
    result = 0
    x = abs(x)
    while x > 0: 
        result = result * 10 + (x % 10)
        x = x // 10
        
    return - 1 * result if is_neg else result

In [32]:
reverse_integer(123), reverse_integer(-123)

(321, -321)

**Rotate a matrix by 90**

In [42]:
import numpy as np
def rotate_a_matrix(m): 
    
    # rotation by 90 : transpose + reflection
    # in-place transpose 
    n = len(m)
    
    for i in range(n):
        for j in range(i+1,n):
            print(f"{i},{j} --> {j},{i}")
            m[i][j], m[j][i] = m[j][i], m[i][j]
            
    print(np.array(m))
    
    # performing reflection
    for i in range(n):
        for j in range(n//2):
            m[i][j], m[i][n-j-1] =  m[i][n-j-1], m[i][j]
    
    return m    
       
matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np.array(rotate_a_matrix(matrix1))

0,1 --> 1,0
0,2 --> 2,0
1,2 --> 2,1
[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

**Split a number into a list**

In [5]:
def split_integer(x:int)-> list:
    splits = []
    while x > 0:
        quotient, remainder = divmod(x, 10)
        splits.append(remainder)
        x = quotient
    return splits[::-1]

split_integer(12345)

[1, 2, 3, 4, 5]

### Greg

Find the closest number to zero.

Given an integer array nums of size n, return the number with the value closest to 0 in nums. If there are multiple answers, return the number with the largest value.
Input: nums = [2,-1,1] <br>
Output: 1<br>
Explanation: 1 and -1 are both the closest numbers to 0, so 1 being larger is returned.<br>

In [9]:
from typing import List
class Solution:
    def findClosestNumber(self, nums: List[int]) -> int:
        closest = nums[0]
        
        for x in nums: 
            if abs(x) < abs(closest): 
                closest = x
        
        if closest < 0 and abs(closest) in nums:
            return abs(closest) 
        else:
            return closest
        
sol = Solution()
sol.findClosestNumber(nums=[-4,-2,1,4,8]), sol.findClosestNumber(nums=[-2,-1,1,5])


(1, 1)

**Merge Strings Alternately**

In [30]:
class Solution:
    def mergeAlternately(self, word1: str, word2: str) -> str:
        A , B = len(word1), len(word2)
        a,b = 0, 0
        result = []
        word = 1
        while a < A and b < B:
            if word == 1:
                result.append(word1[a])
                a += 1
                word = 2
            else: 
                result.append(word2[b])
                b += 1 
                word = 1
                
        while a < A: 
            result.append(word1[a])
            a += 1
            
        while b < B: 
            result.append(word2[b])
            b += 1
        return result
            
        
sol = Solution() 
sol.mergeAlternately(word1="abc",word2="12345"), sol.mergeAlternately("123","abcd")

(['a', '1', 'b', '2', 'c', '3', '4', '5'], ['1', 'a', '2', 'b', '3', 'c', 'd'])

**is subsequence**

Given two strings s and t, return true if s is a subsequence of t, or false otherwise.

A subsequence of a string is a new string that is formed from the original string by deleting some (can be none) of the characters without disturbing the relative positions of the remaining characters. (i.e., "ace" is a subsequence of "abcde" while "aec" is not)

In [35]:
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        S = len(s)
        T = len(t)
        
        if s == "": return True
        if S > T : return False
        
        j = 0 
        for i in range(T): 
            if s[j] == t[i]: 
                # check if we are at the end. 
                # we are at the end small string and there is match.
                if j == S - 1: 
                    return True
                
                j += 1
            
        return False
    
s = Solution()
s.isSubsequence(s="ace", t="abce"), s.isSubsequence(s="abc", t="1234")

(True, False)

**Longest common prefix.**

In [45]:
def longest_prefix(s : list) -> str: 
    
    # find the minimum length 
    min_len = sorted(s, key=len)[0]
    
    for i, c in enumerate(min_len): 
        
        for word in s: 
            if c != word[i]:
                return min_len[:i]
    
    return min_len

input_string = ["flower","flow", "flo"]
longest_prefix(input_string)

'flo'

**Best Time to Buy and Sell Stock**

Input: prices = [7,1,5,3,6,4] <br>
Output: 5 <br>
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.<br>

In [52]:
def best_stock_profit(prices : list) -> int: 
    
    max_profit = 0
    min_price = float('inf')
    
    for i in range(len(prices) -1 ): 
        
        if min_price > prices[i]: 
            min_price = prices[i]
        
        if (prices[i] - min_price) > max_profit: 
            max_profit = prices[i] - min_price
            
    return max_profit
            
best_stock_profit([7,1,5,3,6,4])

5

**Summary Ranges**

Input: nums = [0,1,2,4,5,7] <br>
Output: ["0->2","4->5","7"] <br>

In [63]:
def find_summary_range(input_list : list) -> list:
    
    result = []
    
    i = 0
    while i < len(input_list):

        start = input_list[i]
        while i < len(input_list) - 1 and input_list[i] + 1 == input_list[i+1]:
            i += 1
        
        if start != input_list[i]:
            
            result.append(f"{start}->{input_list[i]}")
            
        else:
            result.append(str(input_list[i] ))
            
        i+= 1
        
    return result

find_summary_range([1,2,3,5])

['1->3', '5']

**Merge Sorted Array**

Store inside the nums1.
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3 <br>
Output: [1,2,2,3,5,6] <br>

In [72]:
def merge(nums1, m, nums2, n):
    x , y = m-1, n-1
    for p in range(m + n - 1, -1, -1):
        if y < 0:
            break
        
        if x>= 0 and nums1[x] > nums2[y]:
            nums1[p] = nums1[x]
            x -= 1
        else:
            nums1[p] = nums2[y]
            y -= 1
    
    return nums1

nums1 = [1, 2, 3, 0, 0, 0]
nums2 = [2, 5, 6]
m,n = 3,3

merge(nums1, m, nums2, n)


[1, 2, 2, 3, 5, 6]